package com.janabo.showgirls.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recommendDaoConfig;
    private final DaoConfig recommendContentDaoConfig;

    private final RecommendDao recommendDao;
    private final RecommendContentDao recommendContentDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recommendDaoConfig = daoConfigMap.get(RecommendDao.class).clone();
        recommendDaoConfig.initIdentityScope(type);

        recommendContentDaoConfig = daoConfigMap.get(RecommendContentDao.class).clone();
        recommendContentDaoConfig.initIdentityScope(type);

        recommendDao = new RecommendDao(recommendDaoConfig, this);
        recommendContentDao = new RecommendContentDao(recommendContentDaoConfig, this);

        registerDao(Recommend.class, recommendDao);
        registerDao(RecommendContent.class, recommendContentDao);
    }
    
    public void clear() {
        recommendDaoConfig.getIdentityScope().clear();
        recommendContentDaoConfig.getIdentityScope().clear();
    }

    public RecommendDao getRecommendDao() {
        return recommendDao;
    }

    public RecommendContentDao getRecommendContentDao() {
        return recommendContentDao;
    }

}
