package com.janabo.showgirls.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import java.util.ArrayList;
import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table RECOMMEND_CONTENT.
*/
public class RecommendContentDao extends AbstractDao<RecommendContent, Void> {

    public static final String TABLENAME = "RECOMMEND_CONTENT";

    /**
     * Properties of entity RecommendContent.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property ImgUrl = new Property(0, String.class, "imgUrl", false, "IMG_URL");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Content = new Property(2, String.class, "content", false, "CONTENT");
        public final static Property TypeId = new Property(3, Long.class, "typeId", false, "TYPE_ID");
    };

    private DaoSession daoSession;

    private Query<RecommendContent> recommend_RecommendContentsQuery;

    public RecommendContentDao(DaoConfig config) {
        super(config);
    }
    
    public RecommendContentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'RECOMMEND_CONTENT' (" + //
                "'IMG_URL' TEXT," + // 0: imgUrl
                "'TITLE' TEXT," + // 1: title
                "'CONTENT' TEXT," + // 2: content
                "'TYPE_ID' INTEGER);"); // 3: typeId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'RECOMMEND_CONTENT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, RecommendContent entity) {
        stmt.clearBindings();
 
        String imgUrl = entity.getImgUrl();
        if (imgUrl != null) {
            stmt.bindString(1, imgUrl);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(3, content);
        }
 
        Long typeId = entity.getTypeId();
        if (typeId != null) {
            stmt.bindLong(4, typeId);
        }
    }

    @Override
    protected void attachEntity(RecommendContent entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public RecommendContent readEntity(Cursor cursor, int offset) {
        RecommendContent entity = new RecommendContent( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // imgUrl
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // content
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // typeId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, RecommendContent entity, int offset) {
        entity.setImgUrl(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setContent(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTypeId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(RecommendContent entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(RecommendContent entity) {
        return null;
    }

    /** @inheritdoc */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "recommendContents" to-many relationship of Recommend. */
    public List<RecommendContent> _queryRecommend_RecommendContents(Long typeId) {
        synchronized (this) {
            if (recommend_RecommendContentsQuery == null) {
                QueryBuilder<RecommendContent> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.TypeId.eq(null));
                recommend_RecommendContentsQuery = queryBuilder.build();
            }
        }
        Query<RecommendContent> query = recommend_RecommendContentsQuery.forCurrentThread();
        query.setParameter(0, typeId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getRecommendDao().getAllColumns());
            builder.append(" FROM RECOMMEND_CONTENT T");
            builder.append(" LEFT JOIN RECOMMEND T0 ON T.'TYPE_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected RecommendContent loadCurrentDeep(Cursor cursor, boolean lock) {
        RecommendContent entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Recommend recommend = loadCurrentOther(daoSession.getRecommendDao(), cursor, offset);
        entity.setRecommend(recommend);

        return entity;    
    }

    public RecommendContent loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<RecommendContent> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<RecommendContent> list = new ArrayList<RecommendContent>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<RecommendContent> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<RecommendContent> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
